import { StyleSheet } from "react-native";

export const MENU_WIDTH = 180;
export const TAB_WIDTH = 36;

export const styles = StyleSheet.create({
  containerRight: {
    position: "absolute",
    right: 0,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 100,
    elevation: 100,
  },
  containerLeft: {
    position: "absolute",
    left: 0,
    top: 0,
    bottom: 0,
    flexDirection: "row",
    alignItems: "center",
    zIndex: 100,
    elevation: 100,
  },
  clip: {
    width: MENU_WIDTH,
    overflow: "hidden",
  },
  menuRight: {
    width: MENU_WIDTH,
    backgroundColor: "#1C1C2A",
    borderTopLeftRadius: 12,
    borderBottomLeftRadius: 12,
    borderWidth: 1,
    borderRightWidth: 0,
    borderColor: "#2E2E4A",
    padding: 12,
    gap: 8,
    elevation: 12,
  },
  menuLeft: {
    width: MENU_WIDTH,
    backgroundColor: "#1C1C2A",
    borderTopRightRadius: 12,
    borderBottomRightRadius: 12,
    borderWidth: 1,
    borderLeftWidth: 0,
    borderColor: "#2E2E4A",
    padding: 12,
    gap: 8,
    elevation: 12,
  },
  tabRight: {
    width: TAB_WIDTH,
    height: 64,
    backgroundColor: "#2E2E4A",
    borderTopLeftRadius: 10,
    borderBottomLeftRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: -2, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 10,
  },
  tabLeft: {
    width: TAB_WIDTH,
    height: 64,
    backgroundColor: "#2E2E4A",
    borderTopRightRadius: 10,
    borderBottomRightRadius: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 2, height: 0 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 10,
  },
  tabIcon: {
    fontSize: 20,
    color: "#9090C0",
    fontWeight: "700",
  },
});
